### ISSUE TITLE
Search no longer working

### ISSUE THREAD

**Issue by mickeprag** [ChrisTerBeke/ThingiBrowser#43]
Hi,

Thank you for this wonderful plugin for Cura.

Just upgraded to version 2.1.0 and now it is no longer possible to search. When entering anything in the search box and pressing search shows no result. The spinner in the bottom of the window just keeps spinning. Is there anything I can do to get more log output to help out with this issue?

Cura 4.6.1 Linux
Thingibrowser 2.1.0

**Comment by ChrisTerBeke** [comment]
I can reproduce this for Thingiverse indeed, MyMiniFactory seems fine. Will investigate and publish a fix if needed.

**Comment by ChrisTerBeke** [comment]
I've investigated and the problem is that Thingiverse decided to make a breaking change to their API (again....). The search results now come back in a 'hits' field instead of being at the root of the JSON response. I'll patch the plugin to parse this correctly and release an update somewhere the coming week.

**Comment by mickeprag** [comment]
Awesome! You are the best!

**Comment by ChrisTerBeke** [comment]
I have submitted a release to Ultimaker to get this fix into the Marketplace. Until then you can try this out locally by dragging the .curapackage file from https://github.com/ChrisTerBeke/ThingiBrowser/releases/tag/v2.1.1 onto the build plate and restart Cura.

**Comment by mickeprag** [comment]
Works perfectly. Although "My Collections" does not work. It just keeps spinning as well. Maybe Thinigverse has changed this API too?
